#!/bin/bash
APP=${!#}

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)

# Backup sources & data
sudo cp -a /var/www/$APP/. $backup_dir/sources

# Copy Nginx
sudo cp -a /etc/nginx/conf.d/$domain.d/$APP.conf $backup_dir/nginx.conf
